### ISSUE TITLE
Abstract viewpoints 

### ISSUE THREAD

**Issue by bjvanderweij** [mtpearce/idyom#28]
Implement a macro in the `viewpoints` package for creating a set of viewpoints based on an abstract viewpoint.

An abstract viewpoint is defined by:

* One or more latent variables that the viewpoint depends on
* A domain associated with each latent variable
* A higher-order function which takes values of the latent variables as input and produces as viewpoint function based on these

**Comment by mtpearce** [comment]
See https://github.com/experiencedlisteners/jackdaw
