### ISSUE TITLE
Define abstract metrical viewpoints

### ISSUE THREAD

**Issue by bjvanderweij** [mtpearce/idyom#29]
Using the abstract viewpoints macro (#28), define the metrical viewpoints below that can be used for metrical inference.

Grid-based

1. Metrical position
2. Metrical accent

Event-based

1. Onset metrical position
2. Offset metrical position
3. Onset metrical accent
4. Offset metrical accent
3. Bar-distance

**Comment by mtpearce** [comment]
See https://github.com/experiencedlisteners/jackdaw
